application:
  knowledge graph

resource:
  gpus: [0, 1]
  cpu_per_gpu: 4
  dim: 256

format:
  delimiters: "\t"

graph:
  file_name: ./data/split/train_s.txt

build:
  optimizer:
    type: Adam
    lr: 1.0e-5
    weight_decay: 1.0e-9
  num_partition: 16
  num_negative: 64
  batch_size: 100000
  episode_size: 30

train:
  model: ComplEx
  num_epoch: 5000
  relation_lr_multiplier: 1
  l3_regularization: 2.0e-3
  sample_batch_size: 2000
  adversarial_temperature: 2
  log_frequency: 1000

evaluate:
  - task: link prediction
    file_name: ./data/split/valid_s.txt
    target: head
    # fast_mode: 10000
  # - task: link prediction
  #   file_name: ./data/split/of_s.txt
  #   target: head
  #   fast_mode: 10000

save:
  file_name: ./results/graphvite/knowledge_graph_embedding/r_complex_1_2e-3.pkl
  save_hyperparameter: true
