application:
  knowledge graph

resource:
  gpus: [0, 1, 2, 3]
  cpu_per_gpu: auto
  dim: 512

format:
  delimiters: "\t"

graph:
  file_name: ./data/split/train_s.txt

build:
  optimizer:
    type: SGD
    lr: 1.0e-2
    weight_decay: 5e-7
  num_partition: auto
  num_negative: 64
  batch_size: 100000
  episode_size: 200

train:
  model: RotatE
  num_epoch: 1000
  margin: 6
  sample_batch_size: 2000
  adversarial_temperature: 0.2
  relation_lr_multiplier: 1
  log_frequency: 500

evaluate:
  - task: link prediction
    file_name: ./data/split/train_u.txt

save:
  file_name: ./results/knowledge_graph_embedding/rotate.pkl
  save_hyperparameter: true
