application:
  knowledge graph

resource:
  gpus: [0, 1, 2, 3]
  cpu_per_gpu: 7
  dim: 512

format:
  delimiters: "\t"

graph:
  file_name: ./data/split/train_s.txt

build:
  optimizer:
    type: Adam
    lr: 1.0e-5
    weight_decay: 1.0e-9
  num_partition: 16
  num_negative: 64
  batch_size: 100000
  episode_size: 30

train:
  model: RotatE
  num_epoch: 5000
  margin: 6
  sample_batch_size: 2000
  adversarial_temperature: 2
  relation_lr_multiplier: 1
  log_frequency: 1200

evaluate:
  - task: link prediction
    file_name: ./data/split/train_u.txt
    # fast_mode: 10000

save:
  file_name: ./results/graphvite/knowledge_graph_embedding/rotate.pkl
  save_hyperparameter: true
