application:
  knowledge graph

resource:
  gpus: [0, 1, 2, 3]
  cpu_per_gpu: 7
  dim: 512

format:
  delimiters: "\t"

graph:
  file_name: ./data/split/train_s.txt

build:
  optimizer:
    type: Adam
    lr: 1.0e-3
    weight_decay: 4.7e-7
  num_partition: 1024
  num_negative: 64
  batch_size: 100000
  episode_size: 100

train:
  model: SimplE
  num_epoch: 4000
  l3_regularization: 2.0e-3
  sample_batch_size: 1000
  adversarial_temperature: 2
  relation_lr_multiplier: 1.0e-4
  log_frequency: 400

evaluate:
  - task: link prediction
    file_name: ./data/split/train_u.txt

save:
  file_name: ./results/knowledge_graph_embedding/simple.pkl
  save_hyperparameter: true
