application:
  knowledge graph

resource:
  gpus: [0, 1]
  cpu_per_gpu: auto
  dim: 512

format:
  delimiters: '\t'

graph:
  file_name: ./data/split/train_s.txt
  as_undirected: true
  normalization: true

build:
  optimizer:
    type: SGD
    lr: 1.0
    weight_decay: 0
  num_partition: auto
  num_negative: 64
  batch_size: 100000
  episode_size: auto

train:
  model: SimplE
  num_epoch: 2000
  relation_lr_multiplier: 1
  l3_regularization: 2.0e-3
  sample_batch_size: 2000
  adversarial_temperature: 2
  relation_lr_multiplier: 1.0e-4
  log_frequency: 500

evaluate:
  - task: link prediction
    file_name: ./data/split/train_u.txt
    target: both
    backend: graphvite

save:
  file_name: ./results/knowledge_graph_embedding/simple.pkl
  save_hyperparameter: true
